version : '3.9'

services:

  db:
    image: postgres:16.1-alpine3.19
    env_file:
      - .env.docker
    volumes:
      - pg_data_1:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5433:5432'

  app:
    build: .
    env_file:
      - .env.docker
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data_1:
